name: Advent of Code
author: mattdsteele
description: Sync with Advent of Code
inputs:
  AOC_SESSION_COOKIE:
    description: Session cookie
    required: true
  AOC_USER:
    description: User ID 
  AOC_YEAR:
    description: Year of competition
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: cloud
  color: purple
